# Generated by Django 3.2.7 on 2021-09-25 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CnabImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Caminho do Arquivo')),
                ('recurrence_rule', models.CharField(blank=True, max_length=255, null=True, verbose_name='Regra de Recorrência')),
                ('done', models.BooleanField(default=False, verbose_name='Feito')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('done_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Feito')),
                ('rows_imported', models.IntegerField(blank=True, null=True, verbose_name='Linhas Importadas')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='template_fiels', to='backend.importtemplate', verbose_name='Template de importação')),
            ],
            options={
                'verbose_name': 'Importação de Arquivo CNAB',
                'verbose_name_plural': 'Importações de Arquivo CNAB',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Loja')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Saldo Inicial')),
            ],
            options={
                'verbose_name': 'Loja',
            },
        ),
        migrations.CreateModel(
            name='ShopImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnab_import', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='imports', to='api.cnabimport', verbose_name='Importação CNAB')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shops', to='api.shop', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Importações da Loja',
                'verbose_name_plural': 'Importações das Lojas',
            },
        ),
    ]
