# Generated by Django 3.2.7 on 2021-09-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnabimport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='parser/%Y/%m/%d/', verbose_name='Arquivo CNAB'),
        ),
    ]
